export const SetList = [
  ["Song", "Artist"],
  ["Accidentally In Love", "Counting Crows"],
  ["Ain't No Sunshine", "Bill Withers"],
  ["Authority Song", "John Mellencamp"],
  ["Bad Time", "Grand Funk Railroad"],
  ["Badge", "Cream"],
  ["Black Friday", "Steely Dan"],
  ["Born To Be Wild", "Steppenwolf"],
  ["Born Under A Bad Sign", "Eric Clapton"],
  ["Carry On Wayward Son", "Kansas"],
  ["Come Together", "The Beatles"],
  ["Every Little Thing She Does Is Magic", "The Police"],
  ["Evil Ways", "Santana"],
  ["Feeling Alright", "Joe Cocker"],
  ["Free Fallin'", "Tom Petty"],
  ["Get Lucky", "Daft Punk"],
  ["Gimme Some Lovin", "Spencer Davis Group"],
  ["Good Times, Bad Times", "Led Zeppelin"],
  ["Higher Ground", "Red Hot Chili Peppers"],
  ["Hold The Line", "Toto"],
  ["Honky Tonk Woman", "The Rolling Stones"],
  ["I Saw Here Standing There", "The Beatles"],
  ["Johnny B Goode", "Chuck Berry"],
  ["Just What I Needed", "The Cars"],
  ["Keep Your Hands To Yourself", "The Georgia Satellites"],
  ["Long Cool Woman", "The Hollies"],
  ["Love Me Dead", "Ludo"],
  ["Low Spark Of High Heeled Boys", "Traffic"],
  ["Mainstreet", "Bob Seger"],
  ["Message In A Bottle", "The Police"],
  ["Midnight Rider", "The Allman Brother Band"],
  ["Mustang Sally", "Wilson Picket"],
  ["My Sharona", "The Knack"],
  ["One Way Out", "The Allman Brother Band"],
  ["Oye Como Va", "Santana"],
  ["Panic Station", "Muse"],
  ["Pinball Wizard", "The Who"],
  ["Play That Funky Music", "Wild Cherry"],
  ["Please Please Me", "The Beatles"],
  ["Pretty Woman", "Roy Orbison"],
  ["Send Her My Love", "Journey"],
  ["Smooth Criminal", "Alien Ant Farm"],
  ["Some Kind Of Wonderful", "Grand Funk Railroad"],
  ["Somebody Told Me", "The Killers"],
  ["Spooky", "Atlanta Rythym Section"],
  ["Story In Your Eyes", "The Moody Blues"],
  ["Suffragette City", "David Bowie"],
  ["Sunshine Of Your Love", "Cream"],
  ["Sunspot Baby", "Bob Seger"],
  ["Surrender", "Cheap Trick "],
  ["The Power Of Love", "Huey Lewis"],
  ["Them Changes", "Buddy Miles"],
  ["Two Tickets To Paradise", "Eddie Money"],
  ["Uptown Funk", "Mark Ronson"],
  ["Werewolves Of London", "Warren Zevon"],
  ["You May Be Right", "Billy Joel"],
  ["Young Lust", "Pink Floyd"]
]
